[package]
name = "test_project"
version = "0.1.0"
edition = "2021"
[dependencies]
rand_chacha = "0.3.1"

[dev-dependencies.cargo-husky]
version = "1.5"
default-features = false
features = ["user-hooks"]
