#!/bin/bash
cargo fmt

git update-index --refresh
git diff-index --quiet HEAD --
UNCOMMITED_CHANGES=$?

if [ $UNCOMMITED_CHANGES != 0 ]; then
  echo "Uncommited changed detected. try stashing them?"
  echo "aborting..."
  exit 1
fi

# Run cargo test
echo "Running cargo test..."
cargo test

# Capture the exit code of cargo test
TEST_EXIT_CODE=$?

# If the test fails, prevent the push
if [ $TEST_EXIT_CODE -ne 0 ]; then
  echo "Cargo test failed. Push aborted"
  echo "to pop stash (run git stash pop)"
  exit 1
fi

echo "Cargo test passed. unstashing and proceeding with push."
exit 0
